name: t2hm-visualizer
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.12.7
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - addict==2.4.0
      - aitviewer==1.13.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.0
      - attrs==25.3.0
      - blinker==1.9.0
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - click==8.2.1
      - comm==0.2.2
      - configargparse==1.7.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - dash==3.0.4
      - decorator==5.2.1
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.13.1
      - flask==3.0.3
      - fonttools==4.58.4
      - fsspec==2024.6.1
      - glcontext==3.0.0
      - idna==3.10
      - imgui==2.0.0
      - importlib-metadata==8.7.0
      - ipython==9.3.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.8
      - markupsafe==2.1.5
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - moderngl==5.12.0
      - moderngl-window==3.1.1
      - mpmath==1.3.0
      - narwhals==1.42.1
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - open3d==0.19.0
      - opencv-contrib-python-headless==4.12.0.88
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.3.0
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.8
      - plotly==6.1.2
      - prompt-toolkit==3.0.51
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycocotools==2.0.10
      - pyglet==2.1.12
      - pyglm==2.8.3
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.18
      - pyqt5-sip==12.18.0
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.4
      - retrying==1.3.4
      - roma==1.5.4
      - rpds-py==0.25.1
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - six==1.17.0
      - smplx==0.1.28
      - stack-data==0.6.3
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - torch==2.6.0+cu124
      - torchaudio==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trimesh==3.23.5
      - triton==3.2.0
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - urllib3==2.4.0
      - usd-core==25.11
      - wcwidth==0.2.13
      - websockets==16.0
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.14
      - zipp==3.23.0
prefix: /home/hlz/anaconda3/envs/t2hm-visualizer
